#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "akamai-ai-markdown"
version = "0.1.0"
authors = ["Jorge Geronimo"]
description = "akamai-ai-markdown"

[[trigger.http]]
route = "/..."
component = "akamai-ai-markdown"

[component.akamai-ai-markdown]
source = "target/wasm32-wasip1/release/akamai_ai_markdown.wasm"
allowed_outbound_hosts = ["https://*:*"]

[component.akamai-ai-markdown.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
